# Generated by Django 3.1.3 on 2021-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
